### ISSUE TITLE
Upload test status in YAML instead of or in addition to Markdown

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/oscar-ci#26]
Thanks to @rbehrends for creating https://github.com/oscar-system/oscar-ci-status ! Now I'd like to ask for some specific improvements:

could you please put the data instead or in addition into a file `_data/ci.yml`, in YAML format? That could look like this:
```yaml
build: 8371
tests:
  - name: Hecke.jl
    success: false
    status: 1
    log: https://oscarci.mathematik.uni-kl.de/job/oscar/8371/artifact/logs/build-8371/Hecke.jl.log
    start: "2020-03-25 16:02"
    duration: 1086
    last_success: 8369
    first_failure: 8370
  - name: CheckPackages.jl
    success: true
    status: 0
    log: https://oscarci.mathematik.uni-kl.de/job/oscar/8371/artifact/logs/build-8371/CheckPackages.jl.log
    start: "2020-03-25 16:02"
    duration: 27
    last_success: 8371
    first_failure: false
...
```
Then I can add a nice `index.html` to render this to
